import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Platform } from 'react-native';

import { WorkoutSession } from '../store/gymStore';
import { Habit } from '../store/habitStore';
import { NutritionMealEntry, NutritionGoal } from '../store/nutritionStore';
import { WeightEntry } from '../store/weightStore';
import { format, subDays } from 'date-fns';

interface WeeklyReportData {
  weekLabel: string;
  sessions: WorkoutSession[];
  habits: Habit[];
  entries: NutritionMealEntry[];
  goal: NutritionGoal;
  weightEntries: WeightEntry[];
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

export async function generateWeeklyPDF(data: WeeklyReportData): Promise<string> {
  const { weekLabel, sessions, habits, entries, goal, weightEntries } = data;

  const totalVolume = sessions.reduce((s, session) => s + session.totalVolume, 0);
  const totalDuration = sessions.reduce((s, session) => s + session.durationSeconds, 0);
  const avgDuration = sessions.length ? Math.round(totalDuration / sessions.length / 60) : 0;

  const nutritionTotals = entries.reduce(
    (acc, e) => ({ calories: acc.calories + e.calories, protein: acc.protein + e.protein, carbs: acc.carbs + e.carbs, fats: acc.fats + e.fats }),
    { calories: 0, protein: 0, carbs: 0, fats: 0 }
  );

  const habitRows = habits.map((h) => {
    const done = h.completions.length;
    return `<tr><td>${escapeHtml(h.name)}</td><td>${done} completions</td><td>🔥 ${h.streak} streak</td></tr>`;
  }).join('');

  const sessionRows = sessions.map((s) => {
    return `<tr><td>${escapeHtml(s.dayName)}</td><td>${format(new Date(s.startedAt), 'MMM d')}</td><td>${Math.round(s.totalVolume)} kg</td><td>${Math.round(s.durationSeconds / 60)}m</td></tr>`;
  }).join('');

  const html = `
    <html>
      <head>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; padding: 24px; color: #1a1a1a; }
          h1 { font-size: 24px; margin-bottom: 8px; }
          h2 { font-size: 18px; margin-top: 24px; margin-bottom: 12px; color: #333; }
          table { width: 100%; border-collapse: collapse; margin-top: 8px; }
          th, td { text-align: left; padding: 8px; border-bottom: 1px solid #eee; }
          th { font-weight: 600; color: #666; font-size: 12px; text-transform: uppercase; }
          .summary { display: flex; gap: 16px; margin-bottom: 16px; }
          .card { background: #f7f7fa; border-radius: 12px; padding: 12px; flex: 1; }
          .card-value { font-size: 20px; font-weight: 700; }
          .card-label { font-size: 11px; color: #666; margin-top: 4px; }
        </style>
      </head>
      <body>
        <h1>IronLog Weekly Report</h1>
        <p style="color:#666;margin-bottom:16px;">${weekLabel}</p>

        <div class="summary">
          <div class="card"><div class="card-value">${sessions.length}</div><div class="card-label">Workouts</div></div>
          <div class="card"><div class="card-value">${Math.round(totalVolume).toLocaleString()}</div><div class="card-label">Volume (kg)</div></div>
          <div class="card"><div class="card-value">${avgDuration}m</div><div class="card-label">Avg Duration</div></div>
          <div class="card"><div class="card-value">${Math.round(nutritionTotals.calories).toLocaleString()}</div><div class="card-label">Avg Calories</div></div>
        </div>

        <h2>Workouts</h2>
        <table>
          <tr><th>Day</th><th>Date</th><th>Volume</th><th>Duration</th></tr>
          ${sessionRows || '<tr><td colspan="4">No workouts this week.</td></tr>'}
        </table>

        <h2>Habits</h2>
        <table>
          <tr><th>Habit</th><th>Total</th><th>Streak</th></tr>
          ${habitRows || '<tr><td colspan="3">No habits tracked.</td></tr>'}
        </table>

        <h2>Nutrition</h2>
        <table>
          <tr><th>Calories</th><th>Protein</th><th>Carbs</th><th>Fats</th></tr>
          <tr>
            <td>${Math.round(nutritionTotals.calories)} / ${goal.calories}</td>
            <td>${Math.round(nutritionTotals.protein)}g / ${goal.protein}g</td>
            <td>${Math.round(nutritionTotals.carbs)}g / ${goal.carbs}g</td>
            <td>${Math.round(nutritionTotals.fats)}g / ${goal.fats}g</td>
          </tr>
        </table>

        <p style="margin-top:40px;color:#999;font-size:11px;text-align:center;">Generated by IronLog</p>
      </body>
    </html>
  `;

  const { uri } = await Print.printToFileAsync({ html });
  return uri;
}

export async function shareWeeklyPDF(data: WeeklyReportData) {
  const uri = await generateWeeklyPDF(data);
  if (Platform.OS === 'web') {
    // On web, open the PDF in a new tab
    window.open(uri, '_blank');
    return;
  }
  await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: 'Share Weekly Report' });
}
